"""add mealplan history and created_by fields

Revision ID: dc6505b9954b
Revises: 5e86cc550475
Create Date: 2026-09-08 13:37:16.300949

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'dc6505b9954b'
down_revision: Union[str, None] = '5e86cc550475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plan_histories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meal_plan_id', sa.UUID(), nullable=False),
    sa.Column('plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_histories_meal_plan_id'), 'meal_plan_histories', ['meal_plan_id'], unique=False)
    op.create_index(op.f('ix_meal_plan_histories_user_id'), 'meal_plan_histories', ['user_id'], unique=False)
    op.add_column('meal_plans', sa.Column('created_by', sa.String(length=20), nullable=False))
    op.add_column('meal_plans', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('todos', sa.Column('created_by', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'created_by')
    op.drop_column('meal_plans', 'version')
    op.drop_column('meal_plans', 'created_by')
    op.drop_index(op.f('ix_meal_plan_histories_user_id'), table_name='meal_plan_histories')
    op.drop_index(op.f('ix_meal_plan_histories_meal_plan_id'), table_name='meal_plan_histories')
    op.drop_table('meal_plan_histories')
    # ### end Alembic commands ###
